[tool.poetry]
name = "telegram-pdf-bot"
version = "0.1.0"
description = "Bot for converting and merging PDF files"
authors = ["Твоё имя или ник"]

[tool.poetry.dependencies]
python = "^3.10"
python-telegram-bot = "^20.0"
pdfkit = "^1.0.0"
PyPDF2 = "^3.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
